# Generated by Django 2.1.7 on 2019-03-26 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post_UserInfo_comment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_model',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
